# Generated by Django 5.0 on 2024-01-03 09:15

import django.core.validators
import django.db.models.deletion
import goals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.TextField(blank=True, null=True)),
                ('metrics', models.JSONField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('group', 'Group')], default='private', max_length=20)),
                ('progress', models.FloatField()),
                ('milestones', models.JSONField()),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv']), goals.models.validate_file_size])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
