# Generated by Django 4.2.7 on 2024-01-03 09:24

import django.core.validators
from django.db import migrations, models
import goals.models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='metrics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='milestones',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='progress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv']), goals.models.validate_file_size]),
        ),
    ]
